# terraform/outputs.tf

output "bastion_public_ip" {
  description = "Public IP of the bastion host"
  value       = aws_instance.bastion.public_ip
}

output "bastion_private_ip" {
  description = "Private IP of the bastion host"
  value       = aws_instance.bastion.private_ip
}

output "control_plane_private_ips" {
  description = "Comma-separated private IPs of control plane nodes"
  value       = join(",", aws_instance.control_plane[*].private_ip)
}

output "control_plane_instance_ids" {
  description = "Instance IDs of control plane nodes"
  value       = aws_instance.control_plane[*].id
}

output "worker_private_ips" {
  description = "Comma-separated private IPs of worker nodes"
  value       = join(",", aws_instance.worker[*].private_ip)
}

output "worker_instance_ids" {
  description = "Instance IDs of worker nodes"
  value       = aws_instance.worker[*].id
}

output "nlb_dns_name" {
  description = "DNS name of the Kubernetes API Network Load Balancer"
  value       = aws_lb.k8s_api.dns_name
}

output "nlb_zone_id" {
  description = "Zone ID of the Kubernetes API NLB (for Route53 alias)"
  value       = aws_lb.k8s_api.zone_id
}

output "cluster_name" {
  description = "Cluster name used as prefix for all resources"
  value       = var.cluster_name
}

output "ssh_config" {
  description = "SSH configuration snippet to add to ~/.ssh/config for bastion tunneling"
  value = <<-EOT

# Add to ~/.ssh/config for Kubernetes cluster access:
Host ${var.cluster_name}-bastion
  HostName ${aws_instance.bastion.public_ip}
  User ubuntu
  IdentityFile ~/.ssh/${var.ssh_key_name}
  StrictHostKeyChecking no

Host ${var.cluster_name}-cp-*
  ProxyJump ${var.cluster_name}-bastion
  User ubuntu
  IdentityFile ~/.ssh/${var.ssh_key_name}
  StrictHostKeyChecking no

Host ${var.cluster_name}-worker-*
  ProxyJump ${var.cluster_name}-bastion
  User ubuntu
  IdentityFile ~/.ssh/${var.ssh_key_name}
  StrictHostKeyChecking no
EOT
}

output "ansible_inventory" {
  description = "Ansible inventory generated from Terraform"
  value = <<-EOT
# Generated by Terraform — do not edit manually
[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/${var.ssh_key_name}
ansible_python_interpreter=/usr/bin/python3

[kube_control_plane]
${join("\n", [for i, ip in aws_instance.control_plane[*].private_ip : "${var.cluster_name}-cp-${i + 1} ansible_host=${ip}"])}

[kube_workers]
${join("\n", [for i, ip in aws_instance.worker[*].private_ip : "${var.cluster_name}-worker-${i + 1} ansible_host=${ip}"])}
EOT
}
